# Cloudflare Pages configuration
# This file provides default settings for Cloudflare Pages
# Note: GitHub Actions deployment uses these settings

name = "agency-saas-boilerplate"
compatibility_date = "2024-01-15"

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"

# Environment variables (add in Cloudflare Dashboard)
# Production variables are set in Cloudflare Pages settings
[env.production]
# Add production environment variables in Cloudflare Dashboard

