# Cloudflare Pages configuration
# This file provides default settings for Cloudflare Pages
# Note: Build commands are configured in Cloudflare Dashboard, not here

name = "agency-saas-boilerplate"
compatibility_date = "2024-01-15"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables (add in Cloudflare Dashboard or here)
# Production variables are set in Cloudflare Pages settings
[env.production]
# Add production environment variables in Cloudflare Dashboard

# Optional: Add environment variables for all environments
[vars]
TO_EMAIL = "jesselhuss@gmail.com"
FROM_EMAIL = "admin@jessehuss.com"

