# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: jessehuss/saas-engine-boilerplate
  branch: master
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/b527b697-7160-4d4b-a533-fd8c85940240/pkce
  auth_token_endpoint: /sites/b527b697-7160-4d4b-a533-fd8c85940240/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://template.jessehuss.com

media_folder: public/assets/uploads
public_folder: /assets/uploads

collections:
  # Blog Posts
  - name: blog
    label: Blog Posts
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Published Date
        name: date
        widget: datetime
        default: ""
        required: true
      - label: Description
        name: description
        widget: text
        required: false
      - label: Author
        name: author
        widget: string
        default: "Admin"
        required: false
      - label: Featured Image
        name: image
        widget: image
        required: false
      - label: Tags
        name: tags
        widget: list
        default: []
        field: { label: Tag, name: tag, widget: string }
      - label: Body
        name: body
        widget: markdown
        required: true

  # Site Settings
  - name: settings
    label: Site Settings
    files:
      - label: Hero Section
        name: hero
        file: src/content/settings/hero.yml
        fields:
          - label: Headline
            name: headline
            widget: string
            hint: "Main headline text for the hero section"
          - label: Subheadline
            name: subheadline
            widget: text
            hint: "Subheadline or description text"
          - label: CTA Button Text
            name: ctaText
            widget: string
            hint: "Text for the call-to-action button"
          - label: CTA Button Link
            name: ctaLink
            widget: string
            hint: "URL for the CTA button (e.g., /contact)"

      - label: About Section
        name: about
        file: src/content/settings/about.yml
        fields:
          - label: Title
            name: title
            widget: string
            hint: "Title for the About section"
          - label: Description
            name: description
            widget: text
            hint: "About section description/body text"
          - label: About Image
            name: image
            widget: image
            required: false
            hint: "Optional image for the About section"

      - label: Navigation
        name: navigation
        file: src/content/settings/navigation.yml
        fields:
          - label: Navigation Items
            name: items
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
                required: true
              - label: URL
                name: href
                widget: string
                required: true

      - label: Social Media
        name: social
        file: src/content/settings/social.yml
        fields:
          - label: Twitter
            name: twitter
            widget: string
            required: false
          - label: Facebook
            name: facebook
            widget: string
            required: false
          - label: Instagram
            name: instagram
            widget: string
            required: false
          - label: LinkedIn
            name: linkedin
            widget: string
            required: false
          - label: GitHub
            name: github
            widget: string
            required: false

  # Services
  - name: services
    label: Services
    folder: src/content/services
    create: true
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: text
        required: true
      - label: Icon
        name: icon
        widget: string
        hint: "Emoji or icon (e.g., 🌱)"
        required: false
